spring.application.name=LookAtMe
spring.datasource.name=lookatme
spring.jpa.show-sql=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/lookatme?serverTimezone=UTC&rewriteBatchedStatements=true&character_set_server=utf8mb4&useUnicode=yes&collation_database=utf8mb4_unicode_ci
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

spring.datasource.hikari.data-source-properties.useUnicode=true
spring.datasource.hikari.data-source-properties.characterEncoding=UTF-8

# Number of ms to wait before throwing an exception if no connection is available.
spring.datasource.tomcat.max-wait=10000

# Maximum number of active connections that can be allocated from this pool at the same time.
spring.datasource.tomcat.max-active=50

# Validate the connection before borrowing it from the pool.
spring.datasource.tomcat.test-on-borrow=true

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

geoname.base.child=http://www.geonames.org/childrenJSON?geonameId={geoNameId}&style=short
base.geoname = 1269750
geoname.postal.codes.by.city=api.geonames.org/postalCodeSearchJSON?placename={city}&username=ugoel1&style=short

geoname.postal.code.validate=http://api.geonames.org/postalCodeLookupJSON?username=ugoel1&postalcode={postalcode}&country={countryCode}&style=short&placename={city}

spring.jpa.properties.hibernate.jdbc.batch_size=2000

# To set logs level as per your need.
logging.level.org.springframework = debug

# To store logs to external file
# Here use strictly forward "/" slash for both Windows, Linux or any other os, otherwise, your logs it won't work.      
logging.file=C:/lookatme.log
#logging.file.max-size: 10MB

# To customize logging pattern.
logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

spring.mandatory-file-encoding=UTF-8
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
file.encoding = UTF-8