roster.rosters[0].shiftStartDay : MONDAY
roster.rosters[0].shiftEndDay : SATURDAY
roster.rosters[0].genericInTime : 08:00:00
roster.rosters[0].totalShiftTime : 09:00:00

roster.rosters[1].shiftStartDay : TUESDAY
roster.rosters[1].shiftEndDay : SUNDAY
roster.rosters[1].genericInTime : 11:00:00
roster.rosters[1].totalShiftTime : 09:00:00

roster.rosters[2].shiftStartDay : MONDAY
roster.rosters[2].shiftEndDay : SATURDAY
roster.rosters[2].genericInTime : 12:00:00
roster.rosters[2].totalShiftTime : 09:00:00

roster.rosters[3].shiftStartDay : TUESDAY
roster.rosters[3].shiftEndDay : SUNDAY
roster.rosters[3].genericInTime : 08:00:00
roster.rosters[3].totalShiftTime : 09:00:00