#!/usr/bin/env bash
# Generates a `.env` file with fresh dev-grade secrets for `docker compose up`.
# Re-running rotates secrets — existing tokens/sessions become invalid.
#
# Usage:  ./scripts/generate-env.sh           # writes ./.env
#         ./scripts/generate-env.sh -f         # overwrite even if .env exists
#         ./scripts/generate-env.sh > custom   # write to stdout (or a chosen file)

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
target="$repo_root/.env"
force=false
to_stdout=false

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required" >&2
  exit 1
fi

while [ $# -gt 0 ]; do
  case "$1" in
    -f|--force) force=true ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "unknown flag: $1" >&2; exit 2 ;;
  esac
  shift
done

# When stdout is not a tty, write there instead of the file.
if [ ! -t 1 ]; then
  to_stdout=true
fi

if ! $to_stdout && [ -e "$target" ] && ! $force; then
  echo "$target already exists. Use -f to overwrite." >&2
  exit 1
fi

jwt_secret="$(openssl rand -base64 64 | tr -d '\n')"
aes_key="$(openssl rand -base64 32 | tr -d '\n')"

priv_pem="$(openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 2>/dev/null)"
priv_b64="$(printf '%s' "$priv_pem" \
  | openssl pkcs8 -topk8 -inform PEM -outform DER -nocrypt 2>/dev/null \
  | base64 | tr -d '\n')"
pub_b64="$(printf '%s' "$priv_pem" \
  | openssl rsa -pubout -outform DER 2>/dev/null \
  | base64 | tr -d '\n')"

emit() {
  cat <<EOF
# Generated by scripts/generate-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DEV USE ONLY. Do not commit. Rotate before any non-dev deployment.

POSTGRES_DB=groomify
POSTGRES_USER=groomify
POSTGRES_PASSWORD=groomify-dev

GROOMIFY_PORT=8080

REDIS_COMMANDER_PORT=8081

APP_JWT_SECRET=$jwt_secret
APP_AES_KEY=$aes_key
RSA_PUBLIC_KEY=$pub_b64
RSA_PRIVATE_KEY=$priv_b64

GROOMIFY_CORS_ALLOWED_ORIGINS=

GEONAMES_USERNAME=your-geonames-username
EOF
}

if $to_stdout; then
  emit
else
  emit > "$target"
  chmod 600 "$target"
  echo "Wrote $target ($(wc -c < "$target" | tr -d ' ') bytes)" >&2
fi
